### ISSUE TITLE
UI/UX notes

### ISSUE THREAD

**Issue by martinmCGG** [Climber-Tools/Cled#1]
Here are a few notes I took when playing around with the editor.
- Loading a "hold" .yaml file (File -> New) instead of a "wall" does not warn the user; causing an empty scene. I would prefer an error when the yaml is not a valid "wall" format.
- The controls may be non-intuitive for new users. Adding an optional "cheat sheet" window with the most important buttons+actions available in the current mode/context would be nice.
- WSAD keys move in a horizontal plane and Space/Shift up/down - based on world coordinates and player's azimuth. This causes an issue (moving in an unexpected direction) when looking exactly up or down. Maybe WSAD are intended to keep player's the altitude, in which case this is OK. Otherwise the following alternative controls would avoid it: W/S could move the player forward/backward in the view direction (possibly changing the altitude), A/D sideways (keeping the altitude since the "up" direction is always vertical), and Space/Shift could move the player up/down (but also possibly changing the position in the horizontal plane when not looking straight)
- Constant blue background is non-distracting but does not aid user orientation. Maybe adding a "skybox" or some (spherical) coordinates around the scene would be a nice improvement. It may be useful in climbing environments which are not as enclosed as the example wall.
- Adding many point lights to the scene reduces the performance. Consider using deferred shading instead of the forward mode.
- When the frame rate is low, player's inertia takes longer to stop. Consider computing the physics separately from the rendering frame rate (Update vs. FixedUpdate).
- There is a typo "GLPv3" in Help>About. Please fix it to make RMS proud :D

Thanks for sharing and good luck with your project!

**Comment by xiaoxiae** [comment]
Thank you for the feedback (both here and in SIS)! I've added the points to my TODO list and will try to address them in the next update.
